stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/raw
    params:
    - data_preprocessing.fillna_categorical
    - data_preprocessing.fillna_numeric
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - data/interim
    params:
    - feature_engineering.max_features
    - feature_engineering.encode_unknown_value
    outs:
    - data/processed

  model_building:
    cmd: python src/model_building.py
    deps:
    - src/model_building.py
    - data/processed
    params:
    - model_building.n_estimators
    - model_building.early_stopping_rounds
    - model_building.max_depth
    - model_building.eta
    - model_building.subsample
    - model_building.colsample_bytree
    - model_building.random_state
    - model_building.n_splits
    outs:
    - models/

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - models/xgb_model_fold_1.pkl
    - data/processed/train_features.csv
    params:
    - model_evaluation.average
    - model_evaluation.zero_division
    metrics:
    - reports/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
