data_preprocessing:
  fillna_categorical: "unknown"
  fillna_numeric: "mean"

feature_engineering:
  max_features: 35
  encode_unknown_value: -1

model_building:
  n_estimators: 500
  early_stopping_rounds: 25
  max_depth: 5
  eta: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
  n_splits: 4

model_evaluation:
  average: "weighted"
  zero_division: 0
